kind: pipeline
name: default
type: kubernetes

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: registry.makerforce.io
    repo: registry.makerforce.io/pwd/caddy
    tags:
    - latest
    context: scratch
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
