kind: pipeline
type: docker
name: default

steps:
- name: caddyversion_update
  image: hairyhenderson/dockerfiles-builder:latest
  commands:
  - make update
  when:
    event:
    - cron
    cron:
    - bump_version
- name: caddyversion_commit
  image: appleboy/drone-git-push
  setting:
    branch: master
    remote: git@github.com:productionwentdown/caddy.git
    commit: true
    commit_message: Bump Caddy version
    ssh_key:
      from_secret: github_ssh_key
  when:
    event:
    - cron
    cron:
    - bump_version
- name: stackbrew_regenerate
  image: hairyhenderson/dockerfiles-builder:latest
  commands:
  - make library/caddy
  when:
    event:
    - push
    - update
    cron:
    - update
- name: stackbrew_commit
  image: appleboy/drone-git-push
  setting:
    branch: master
    remote: git@github.com:productionwentdown/caddy.git
    commit: true
    commit_message: Regenerate stackbrew library
    ssh_key:
      from_secret: github_ssh_key
  when:
    event:
    - push
    - update
    cron:
    - update
- name: dockerhub
  image: hairyhenderson/dockerfiles-builder:latest
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - bashbrew build --pull always caddy
  - echo $PASSWORD | docker login --username $USERNAME --password-stdin
  - bashbrew push caddy
  environment:
    BASHBREW_LIBRARY: ./library
    BASHBREW_NAMESPACE: caddy
    USERNAME:
      from_secret: dockerhub_username
    PASSWORD:
      from_secret: dockerhub_token
  when:
    event:
    - push
    - update
    cron:
    - update

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
