name: Generate stackbrew library

on:
  push:
    branches:
    - master
    paths:
    - '*/Dockerfile'

jobs:
  regenerate_stackbrew:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_GITHUB_TOKEN }}

    - name: Regenerate stackbrew library
      run: make library/caddy

    - name: Configure git
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add library/caddy
        if output=$(git status --porcelain) && [ ! -z "$output" ]; then
          git commit -m 'Regenerate stackbrew library'
          git push
        fi
